import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <div className="w-full">
            <div className="w-full flex justify-evenly p-4 bg-slate-600">
            <a href="/"><span>DreamVault Logo</span></a>
             <div className="flex flex-row">
            <a href="/">Home</a >
            <a href="/about">About</a >
            <a href="/signup">SignUp</a >
            <a href="/signin">SignIn</a >
            <a className='bg-yellow-400' href="/addevent">Raise Fund</a >
            </div>
        </div>
        </div>

      {children}
      
      </body>
    </html>
  )
}
